### PR TITLE
added a function "str_shuffle" .

### PR DESCRIPTION
**Pull request by rahul-devrani**
Added a function "str_shuffle" which randomly shuffle characters of a string.

### CODE REVIEW

**Comment by SharonIV0x86** [comment]
Your implementation is good. I have a few suggestions or optional changes which you can work on and its entirely upto you. And you can work on them in future by raising an issue.


- During testing i found that the function adds 1-2 new line characters in between the shuffled strings, i tried debugging the issue but i was somewhat related to how are single byte strings passed and etc etc. The only solution i found was to remove new line characters, carriage return, and trailing white spaces. 

- Another suggestion of mine is that while shuffling we ignore the white space characters, like let the user choose if they want to shuffle white spaces also or not by passing argument to the function. And if user chooses to not to shuffle white space characters we keep the position of them as it is in the string.

One last thing i want to mention was that, if you want to work on a issue or add a new feature, comment on that issue and i will assign it to you, then you can go ahead and make the pull request, for this feature you should've commented on this [issue](https://github.com/SharonIV0x86/StringWiz/issues/10) that you would like to work on it, and i would have assigned it to you. 
Pls make sure to follow [Contribution guide](https://github.com/SharonIV0x86/StringWiz?tab=readme-ov-file#contributing). 👍 👍

**Comment by rahul-devrani** [comment]
Sure, I understand. Please assign me the issue, and I'll make sure to follow the contribution guidelines while working on it. Thanks!

**Comment by rahul-devrani** [comment]
I have made some updates to the code. Please take a moment to review it and provide your feedback.

**Review by SharonIV0x86 — APPROVED** [review]
Good to go, will require optional changes change in future. 👍

**Pull request merged**
